function Hd = FIR_Equiripple
%FIR_EQUIRIPPLE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 09-May-2019 19:50:21

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

Fpass1 = 850;              % First Passband Frequency
Fstop1 = 950;              % First Stopband Frequency
Fstop2 = 2000;             % Second Stopband Frequency
Fpass2 = 2100;             % Second Passband Frequency
Dpass1 = 0.057501127785;   % First Passband Ripple
Dstop  = 0.0056234132519;  % Stopband Attenuation
Dpass2 = 0.057501127785;   % Second Passband Ripple
dens   = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
