function Hd = IIR_ChebyshevSingleOrder
%IIR_CHEBYSHEVSINGLEORDER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 09-May-2019 23:07:33

% Chebyshev Type I Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N      = 6;     % Order
Fpass1 = 850;   % First Passband Frequency
Fpass2 = 2100;  % Second Passband Frequency
Apass  = 1;     % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandstop('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
Hd = design(h, 'cheby1');

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);



% [EOF]
